name: Atualizar Preços das Hospedagens

on:
  schedule:
    - cron: '0 10 * * *'  # Todo dia às 10h UTC
  workflow_dispatch:  # Permite rodar manualmente

permissions:
  contents: write  # Permissão para escrever arquivos

jobs:
  atualizar-precos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Configurar Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
    - name: Atualizar preços
      run: |
        cat > precos.json << 'EOF'
        {
          "ultima_atualizacao": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "hospedagens": {
            "hostinger": {
              "preco": "7,49",
              "moeda": "R$",
              "link_afiliado": "https://seu-link-afiliado-hostinger"
            },
            "hostgator": {
              "preco": "11,90", 
              "moeda": "R$",
              "link_afiliado": "https://seu-link-afiliado-hostgator"
            },
            "bluehost": {
              "preco": "2,75",
              "moeda": "US$",
              "link_afiliado": "https://seu-link-afiliado-bluehost"
            },
            "kinsta": {
              "preco": "32",
              "moeda": "US$",
              "link_afiliado": "https://seu-link-afiliado-kinsta"
            },
            "siteground": {
              "preco": "2,89",
              "moeda": "US$",
              "link_afiliado": "https://seu-link-afiliado-siteground"
            }
          }
        }
        EOF
        
        # Atualizar data
        sed -i "s/$(date -u +%Y-%m-%dT%H:%M:%SZ)/$(date -u +%Y-%m-%dT%H:%M:%SZ)/g" precos.json
        
    - name: Commit alterações
      run: |
        git add precos.json
        if git diff --staged --quiet; then
          echo "Nenhuma alteração para commitar"
        else
          git commit -m "🤖 Atualizar preços automaticamente - $(date)"
          git push
        fi
